export const IMAGE_DEFAULT_MIME = "image/png"

export const IMAGE_MAX_DIMENSION = 1024
export const IMAGE_VERTEX_DIMENSION_UNIT = 384

export const IMAGE_BRIGHTNESS_FACTOR = 120
export const IMAGE_CONTRAST_FACTOR = 110
export const IMAGE_QUALITY_FACTOR = 0.9
